const test = require('node:test');
const assert = require('node:assert/strict');
const app = require('firebase-admin/app'), auth = require('firebase-admin/auth');
const firestore = require('firebase-admin/firestore'), storage = require('firebase-admin/storage');
const { SYNTHETIC_FIXTURE: f, SYNTHETIC_AUDIT_ID: auditId, approvedFixtureRequest, fixtureRuntimeMatches } = require('../lib/synthetic-fixture-domain');
let state, files, writes, deletes, authChecks, revoked, authority, reads, storageFailure;
const listingPath='listings/'+f.listingId, auditPath='adminAuditEvents/'+auditId;
function snap(path) { const d=state.get(path); return {exists:d!==undefined,data:()=>d}; }
function reference(path) { return {path,collection:name=>query(path+'/'+name)}; }
function query(path) { const q={path,fields:null,doc:id=>reference(path+'/'+id),where(field,op,value){assert.equal(field,'listingId');assert.equal(op,'==');assert.equal(value,f.listingId);return q;},select(...fields){q.fields=fields;return q;},limit(n){assert.equal(n,50);return q;}};return q; }
const db={doc:reference,collection:query,async runTransaction(fn){const pending=[];const result=await fn({
 async get(ref){reads.push(ref.path);return ref.fields!==undefined?{empty:!(state.get(ref.path)?.length),docs:(state.get(ref.path)??[]).map(data=>({data:()=>data}))}:snap(ref.path);},
 update(ref,data){pending.push(['update',ref.path,data]);},create(ref,data){assert(!state.has(ref.path));pending.push(['create',ref.path,data]);}
 });for(const [kind,path,data]of pending){writes.push({kind,path});const next={...state.get(path)};for(const[k,v]of Object.entries(data)){if(k==='summary.mediaComplete')next.summary={...next.summary,mediaComplete:v};else next[k]=v;}state.set(path,next);}return result;}};
Object.defineProperty(app,'getApp',{value:()=>({options:{projectId:f.projectId,storageBucket:f.bucket}})});
Object.defineProperty(firestore,'getFirestore',{value:()=>db});
Object.defineProperty(auth,'getAuth',{value:()=>({async verifyIdToken(token,checkRevoked){assert.equal(token,'placeholder');assert.equal(checkRevoked,true);authChecks++;if(revoked)throw Error('revoked');return {uid:'admin-test',admin:true,exp:Math.floor(Date.now()/1000)+3600};},async getUser(){return {disabled:false,customClaims:{admin:authority}};}})});
Object.defineProperty(storage,'getStorage',{value:()=>({bucket(name){assert.equal(name,f.bucket);return {async getFiles(options){assert.deepEqual(options,{prefix:`users/${f.ownerUid}/listings/${f.listingId}/`,autoPaginate:false,maxResults:2});return [files,null];}};}})});
const { cleanupApprovedSyntheticFixture: endpoint } = require('../lib/synthetic-fixture-cleanup');
function reset(){process.env.TAKEME_RELEASE_TARGET='production';process.env.TAKEME_FIREBASE_PROJECT_ID=f.projectId;process.env.GCLOUD_PROJECT=f.projectId;process.env.TAKEME_STORAGE_BUCKETS=f.bucket;
 state=new Map([[listingPath,{sellerId:f.ownerUid,title:f.title,description:f.description,listingType:'buy_now',status:'active',createdAt:firestore.Timestamp.fromDate(new Date(f.createdAt)),imageUrls:[`https://firebasestorage.googleapis.com/v0/b/${f.bucket}/o/${encodeURIComponent(f.objectPath)}?alt=media`]}],['listings/unrelated',{status:'active',sellerId:'real-user'}]]);
 writes=[];deletes=[];reads=[];authChecks=0;revoked=false;authority=true;storageFailure=false;
 files=[{name:f.objectPath,metadata:{name:f.objectPath,generation:f.objectGeneration,size:f.objectSize,contentType:f.contentType},async delete(options){assert.deepEqual(options,{ignoreNotFound:true,ifGenerationMatch:f.objectGeneration});if(storageFailure)throw Error('storage failure');deletes.push(this.name);files=[];}}];
 return {auth:{uid:'admin-test',token:{admin:true}},data:{listingId:f.listingId},rawRequest:{headers:{authorization:'Bearer placeholder'}}};}
async function denied(request,code='permission-denied'){await assert.rejects(()=>endpoint.run(request),e=>e.code===code);assert.equal(writes.length,0);assert.equal(deletes.length,0);}
for(const kind of ['signed-out','normal-user','revoked','removed-claim'])test(kind+' cannot execute cleanup',async()=>{const r=reset();if(kind==='signed-out')r.auth=undefined;if(kind==='normal-user')r.auth.token.admin=false;if(kind==='revoked')revoked=true;if(kind==='removed-claim')authority=false;await denied(r);});
test('arbitrary listing IDs and extra request fields are rejected before data access',async()=>{for(const data of [{listingId:'unrelated'},{listingId:f.listingId,ownerUid:'spoofed'},{},null]){const r=reset();r.data=data;await denied(r);assert.equal(reads.length,0);}});
test('valid admin withdraws exact fixture without reading owner policy acceptance',async()=>{const r=reset();const original=state.get('listings/unrelated');const result=await endpoint.run(r);assert.equal(result.status,'removed');assert.equal(result.alreadyRemoved,false);assert.equal(result.mediaComplete,true);assert.deepEqual(deletes,[f.objectPath]);assert.equal(state.get(listingPath).status,'removed');assert.deepEqual(state.get('listings/unrelated'),original);assert(authChecks>=4);assert(!reads.some(x=>x.includes('private/onboarding')));assert(writes.every(x=>[listingPath,auditPath].includes(x.path)));const event=state.get(auditPath);assert.deepEqual(Object.keys(event).sort(),['action','adminUid','resourceId','resourceType','summary','timestamp']);assert.equal(event.action,'synthetic_fixture_cleanup');assert.equal(event.adminUid,'admin-test');assert.equal(event.summary.reason,f.reason);assert.equal(event.summary.mediaComplete,true);});
test('retries after successful removal do not duplicate audit or delete history',async()=>{const r=reset();await endpoint.run(r);const event=state.get(auditPath);const writeCount=writes.length;const result=await endpoint.run(r);assert.equal(result.alreadyRemoved,true);assert.equal(writes.length,writeCount);assert.deepEqual(state.get(auditPath),event);assert.equal(writes.filter(x=>x.kind==='create').length,1);});
test('already removed exact fixture can finish cleanup idempotently',async()=>{const r=reset();state.get(listingPath).status='removed';assert.equal((await endpoint.run(r)).alreadyRemoved,true);assert.equal(writes.filter(x=>x.path===listingPath).length,0);});
for(const [field,value]of [['title','Different item'],['sellerId','real-user'],['description','Changed marker'],['createdAt',firestore.Timestamp.now()],['listingType','auction'],['status','sold'],['imageUrls',[`https://firebasestorage.googleapis.com/v0/b/${f.bucket}/o/unrelated`]]])test('changed '+field+' aborts all cleanup',async()=>{const r=reset();state.get(listingPath)[field]=value;await denied(r,'failed-precondition');});
test('missing fixture aborts all cleanup',async()=>{const r=reset();state.delete(listingPath);await denied(r,'failed-precondition');});
test('real/unknown user interactions cannot enter destructive history cleanup',async()=>{const r=reset();for(const path of ['offers','transactions','conversations','publicReviews','reports',listingPath+'/bids','listingWatchers/'+f.listingId+'/users','users/'+f.ownerUid+'/notifications'])state.set(path,[{buyerId:'real-user',status:'accepted',evidence:'retained'}]);const before=[...state].filter(([k])=>!k.startsWith('listings/'));const result=await endpoint.run(r);assert.equal(result.historyPresent,true);assert.equal(result.historicalReferencesPreserved,true);for(const[k,v]of before)assert.deepEqual(state.get(k),v);assert(writes.every(x=>[listingPath,auditPath].includes(x.path)));});
for(const kind of ['foreign-path','extra-object','generation','size','mime'])test('media '+kind+' fails before withdrawal/deletion',async()=>{const r=reset();if(kind==='foreign-path')files[0].name='users/real-user/listings/other/image.webp';if(kind==='extra-object')files.push({...files[0],name:`users/${f.ownerUid}/listings/${f.listingId}/unknown.webp`});if(kind==='generation')files[0].metadata.generation='replacement';if(kind==='size')files[0].metadata.size='999';if(kind==='mime')files[0].metadata.contentType='image/jpeg';await denied(r,'failed-precondition');});
test('storage failure leaves withdrawn state and one resumable audit',async()=>{const r=reset();storageFailure=true;await assert.rejects(()=>endpoint.run(r),/storage failure/);assert.equal(state.get(listingPath).status,'removed');assert.equal(state.get(auditPath).summary.mediaComplete,false);storageFailure=false;await endpoint.run(r);assert.equal(writes.filter(x=>x.kind==='create').length,1);assert.equal(state.get(auditPath).summary.mediaComplete,true);});
test('reactivated fixture with existing cleanup audit fails closed',async()=>{const r=reset();await endpoint.run(r);state.get(listingPath).status='active';writes=[];deletes=[];await denied(r,'failed-precondition');});
test('admin lifecycle restriction prevents the operational action',async()=>{const r=reset();state.set('accountLifecycles/admin-test',{state:'deletion_pending'});await denied(r);});
test('resource context rejects staging, wrong bucket and emulator',async()=>{const env={GCLOUD_PROJECT:f.projectId,TAKEME_RELEASE_TARGET:'production',TAKEME_FIREBASE_PROJECT_ID:f.projectId,TAKEME_STORAGE_BUCKETS:f.bucket};assert(fixtureRuntimeMatches(env,f.projectId,f.bucket));for(const patch of [{TAKEME_RELEASE_TARGET:'staging'},{GCLOUD_PROJECT:'different'},{TAKEME_STORAGE_BUCKETS:'other'},{FIRESTORE_EMULATOR_HOST:'localhost:8080'}])assert(!fixtureRuntimeMatches({...env,...patch},f.projectId,f.bucket));assert(!fixtureRuntimeMatches(env,f.projectId,'other'));assert(!approvedFixtureRequest({listingId:'anything'}));});
