export interface HelpSection { id: string; title: string; questions: { question: string; answer: string }[]; links?: { href: string; label: string }[] }

export const helpSections: HelpSection[] = [
  { id: "getting-started", title: "Getting started", questions: [
    { question: "What can I do on TAKEME?", answer: "Browse marketplace items, publish listings for new or preloved goods, message sellers, make offers and participate in auctions. Buyers and sellers arrange their exchange together. TAKEME does not process buyer-to-seller payments or create shipments." },
    { question: "Do I need an account to browse?", answer: "Public listings and this Help Centre are available without login. Sign in with email/password or Google to use account features such as Saved, messaging, offers, bidding and selling. TAKEME V1 is intended for adults aged 18 or older." },
  ], links: [{ href: "/explore", label: "Explore the marketplace" }, { href: "/login", label: "Sign in to TAKEME" }] },
  { id: "buying", title: "Buying", questions: [
    { question: "How do I find and save an item?", answer: "Use Explore search and its available category, condition, price, listing-type and location filters. Select the heart on an item to save it after signing in. Saved keeps items and auctions together with your searches and followed sellers." },
    { question: "How do I contact a seller?", answer: "Open the listing and use Chat. An eligible buyer can start a conversation with the seller; you cannot open a buyer chat on your own listing. Ask about condition, authenticity, accessories, collection or delivery and any costs before agreeing." },
    { question: "Does Buy now mean I paid?", answer: "No. A supported buy-now request can form an agreed deal when accepted. Payment and exchange are arranged with the seller; TAKEME does not run checkout, hold buyer funds or guarantee delivery." },
  ], links: [{ href: "/saved", label: "Open Saved" }] },
  { id: "selling", title: "Selling", questions: [
    { question: "How do I create a listing?", answer: "Open Sell, choose Buy now or Auction, add the supported item details, photos and general location, then review before publishing. Pick a saved meet-up place explicitly if you want it included. Your private address is never used automatically." },
    { question: "Which conditions can I choose?", answer: "New, Like new, Good and Fair. Choose accurately and explain defects or missing accessories in the description. TAKEME does not inspect or authenticate each item." },
    { question: "How do drafts and listing edits work?", answer: "Use Save draft to keep a listing for later, then find it under Profile → My Listings → Drafts. My Listings provides supported edit/status actions. Auction timing and amounts become locked once it starts, and auctions with bids cannot be cancelled by the seller." },
    { question: "Can I sell new or branded items, or act for a business?", answer: "New, branded and preloved goods can be listed when lawful and accurately described. Sellers acting for a business use the available profile/listing tools and remain responsible for their authority and legal obligations. TAKEME does not currently provide dedicated business verification or guarantee authenticity." },
  ], links: [{ href: "/sell", label: "Create a listing" }, { href: "/profile/listings", label: "Manage your listings" }, { href: "/help/prohibited-items", label: "Check prohibited items" }] },
  { id: "offers", title: "Offers and deals", questions: [
    { question: "How do offers and counteroffers work?", answer: "On an available listing that supports offers, use Make Offer and enter your amount. The seller can accept, decline or counter; the buyer can accept a counter. Track the real offer state in Messages or the relevant deal view." },
    { question: "What does an accepted offer mean?", answer: "It records an agreed marketplace amount and deal state. It does not confirm payment or create a shipment. Agree collection/delivery and any costs with the other participant." },
    { question: "How do I complete, cancel or raise a concern about a deal?", answer: "Use the relevant transaction controls. Completion uses both participants’ confirmations. A cancellation request must be accepted through the existing two-party flow. A dispute records a concern and does not automatically resolve it or issue a refund. Do not confirm an exchange that did not happen." },
  ], links: [{ href: "/profile/transactions", label: "View your transactions" }] },
  { id: "auctions", title: "Auctions", questions: [
    { question: "How do I place a bid?", answer: "Open a live, eligible auction, read the item and timing, then use Place Bid. Review the amount before confirming. The first valid bid meets the starting amount; later bids meet the current amount plus the minimum increment. Sign-in is required." },
    { question: "What happens if I am outbid?", answer: "The auction displays your bid state and the minimum next amount. You can bid again while it remains live. Optional outbid alerts can appear in Updates according to your notification preference." },
    { question: "How is the winner determined?", answer: "The accepted highest bid and server finalisation determine the result at the stated end time. An auction without valid bids has no winner. A winner can receive an agreed deal to arrange the exchange with the seller." },
    { question: "Can a seller bid on their own auction?", answer: "No. The backend rejects bids from the auction’s seller." },
    { question: "Do late bids extend the auction?", answer: "No. TAKEME does not currently extend an auction automatically after a late bid. The displayed end time still applies, and submitting at the last moment does not guarantee the server accepts it." },
    { question: "Can I withdraw a bid or delete my account to cancel it?", answer: "There is no buyer bid-withdrawal control. Account deletion preserves legitimate live bids and auction outcomes; live auction obligations can keep deletion pending. Bid carefully." },
  ], links: [{ href: "/explore?type=auction", label: "Explore auctions" }] },
  { id: "messages", title: "Messages and Updates", questions: [
    { question: "Who can see my messages?", answer: "Ordinary conversations are private to their buyer and seller. An authorised review of a reported message/conversation can include limited relevant context. The current messenger supports text; message attachments, typing indicators and read receipts are not available." },
    { question: "Where do marketplace alerts appear?", answer: "Updates contains persisted in-app alerts. Settings → Notifications controls eight supported optional categories; essential offers, transactions, disputes and auction wins remain on. Native push, email/SMS marketplace alerts and daily digests are not active." },
  ], links: [{ href: "/messages", label: "Open Messages" }, { href: "/updates", label: "Open Updates" }, { href: "/notification-preferences", label: "Notification preferences" }] },
  { id: "saved", title: "Saved and following", questions: [
    { question: "Where are my saved items, searches and followed sellers?", answer: "Open Saved to switch between items, searches and sellers. Save a supported Explore query explicitly to receive matching-listing alerts. You can edit, pause/resume or remove saved searches and unfollow sellers through the existing controls." },
    { question: "What does Not interested do?", answer: "Where the action is available in personalised discovery, it hides that listing and offers Undo. It does not block a seller or hide an entire category. Private marketplace activity can influence recommendations." },
  ], links: [{ href: "/saved", label: "Manage Saved" }] },
  { id: "account", title: "Account and privacy", questions: [
    { question: "How do I edit my profile or reset a password?", answer: "Use Settings → Edit profile for the supported photo, display name and general location. Security shows your actual connected providers. Email/password accounts can request Firebase’s reset email; Google accounts use Google’s account security for that credential." },
    { question: "Is my home address public?", answer: "No. A saved private address is account-only. A general profile/listing area can be public. Saved meet-up places are private until you explicitly select a place for a listing; that listing then shows the selected public snapshot." },
    { question: "How do I delete my account?", answer: "Open Settings → Delete account or the public account-deletion page. Sign in to your own account, reauthenticate and confirm. The page explains what is removed, limited retained history and progress/retry. Completion is shown only after required cleanup and Auth deletion succeed." },
    { question: "What does deletion pending mean?", answer: "Live auctions with bids, unfinished accepted deals or unresolved cases can delay final cleanup. Normal marketplace activity stops while necessary resolution access remains. Deletion does not silently cancel a valid bid or fabricate a deal outcome. Read the progress page and use available legitimate resolution actions." },
  ], links: [{ href: "/profile/settings", label: "Account settings" }, { href: "/account-deletion", label: "Deletion information and request" }] },
  { id: "safety", title: "Safety and reporting", questions: [
    { question: "How can I make an exchange safer?", answer: "Keep communication in TAKEME where practical. Never share passwords or verification codes. Ask questions, inspect the item, use a public meet-up place and agree the exchange and costs before proceeding. TAKEME does not provide payment or shipping guarantees." },
    { question: "How do I report suspicious content?", answer: "Use Report listing on an item, Report seller on a seller profile, or Report in a conversation/on another participant’s message. Sign in, choose a relevant reason and add concise details. Reports are submitted for review; no response time or outcome is guaranteed." },
    { question: "Does TAKEME pre-approve every listing or offer buyer protection?", answer: "No. Listing publication does not mean the item has been checked or authenticated. TAKEME currently does not provide escrow, insurance, payment guarantees or guaranteed refunds. Read the listing carefully and report concerns." },
  ], links: [{ href: "/help/prohibited-items", label: "Prohibited items and moderation rules" }] },
];
