import type { InformationSection } from "@/components/public-information/public-information";
import { productionReleasePolicy } from "../../functions/src/release-policy.ts";
import { legalPublicationReadiness } from "../../functions/src/legal-publication.ts";
import { marketplaceOperator } from "./operator.ts";

// English owner draft only. Central approvals control publication and activation.
export const privacyDocument = Object.freeze({
  title: "TAKEME Privacy Notice",
  language: "English",
  version: productionReleasePolicy.privacyVersion,
  minimumAge: productionReleasePolicy.minimumAge,
  effectiveDate: legalPublicationReadiness.effectiveDate,
  lastUpdated: legalPublicationReadiness.lastUpdated,
  operator: marketplaceOperator,
  businessAddress: null,
  businessAddressStatus: "LEGAL REVIEW / OWNER INPUT REQUIRED",
  reviewNotice: "English owner draft for Malaysian legal review. This notice is not in effect and has not been published. Final English and Bahasa Melayu legal approval, the actual public launch date and separate publication approval remain required.",
});

export const privacySections: InformationSection[] = [
  { id: "about", title: "1. Who We Are", paragraphs: [
    "TAKEME is operated by " + marketplaceOperator.name + " (SSM Registration No. " + marketplaceOperator.registrationNumber + "). Our privacy and support contact is " + marketplaceOperator.privacyLegalEmail + ".",
    "This English owner draft explains TAKEME V1 personal-data practices. It is not final Malaysian legal counsel approval or permission to publish or activate the notice.",
  ] },
  { id: "scope", title: "2. Scope of This Privacy Notice", paragraphs: [
    "This notice covers account registration and sign-in, profiles, listings and photos, messages, offers, agreed deals, auctions and bids, in-app Updates, Saved and following, discovery, preferences, reports, support, policy acceptance and account-deletion workflows.",
    "TAKEME helps buyers and sellers arrange their exchange directly. Current V1 does not process payment-card details through Stripe, seller payouts or integrated protected checkout, or provide integrated shipping/AWB, Seller Centre, live commerce or short-video commerce. Future services would require a further privacy review before collection starts.",
    "This draft describes the reviewed web service and planned compliance architecture. It does not certify a future native application or introduce native push notification collection or future V2 analytics.",
  ] },
  { id: "categories", title: "3. What Personal Data We Collect", paragraphs: [
    "Personal data can identify you directly or remain linked to your account or marketplace activity. The categories below cover information you provide, supported activity records generated by the service and identity information supplied by the sign-in provider you choose.",
  ], bullets: [
    "Account and authentication: email, account and provider identifiers, sign-in/account status and relevant timestamps.",
    "Profile and marketplace content: display name, profile photo, voluntarily provided profile information, general area, listings, photos, prices, categories, bids, offers and deal records.",
    "Communications and support: private marketplace messages, support emails, report/complaint details and relevant dispute evidence.",
    "Preferences and activity: Saved items, follows, saved searches, notification settings and supported marketplace discovery signals.",
    "Technical and compliance records: operation identifiers, timestamps, bounded security/rate-control records and explicit Terms/Privacy/18+ acceptance evidence.",
  ] },
  { id: "provided", title: "4. Data Provided by Users", paragraphs: [
    "You provide account information, profile details, listing text/photos and marketplace messages or offers when you use those features. Support emails and reports can contain information you choose to supply.",
    "A profile photo, private address and saved search are optional. Account identity is needed for authenticated features; relevant item details and photos are needed to publish a listing. If you do not supply required information, the relevant feature cannot be completed. You can still browse approved public marketplace content.",
    "Private address lines, postcode, city, state and country are account-only information. Saved meet-up names and general areas remain private until you explicitly select a meet-up snapshot for a listing. Removing a saved place does not automatically change an existing listing snapshot. Do not put a private home address, credentials or unnecessary sensitive details into public text, photos or messages.",
  ] },
  { id: "authentication", title: "5. Account and Authentication Data", paragraphs: [
    "Firebase Authentication handles email/password and Google sign-in. Account data includes your authentication/account identifier, email, connected provider identity, account status and relevant creation/sign-in timestamps. Google sign-in may supply a display name and profile photo associated with the identity you choose.",
    "Firebase handles credentials and sign-in sessions. TAKEME does not store your password in marketplace profile documents or messages. Password-reset emails are authentication messages, separate from marketplace alerts. Account deletion or reauthentication does not delete your Google account.",
    "Public browsing does not require an account. Login, refresh and browsing do not count as Privacy or Terms acceptance. Current explicit Terms/Privacy acceptance and 18+ confirmation are required before protected marketplace writes such as Sell, Chat, Offer, Bid, Save, Follow and uploads.",
  ] },
  { id: "profile", title: "6. Profile Data", paragraphs: [
    "Your public display name, profile photo, membership information, general marketplace district/city and state, and available seller ratings/reviews or reputation may appear to marketplace visitors. A profile or rating is not proof of item authenticity or business registration.",
    "Your account email, private address, private onboarding and policy acceptance records are not part of the public marketplace profile. Public seller projections use permitted marketplace fields; private addresses are not automatically copied to profiles, listings or discovery.",
    "Structured location features use information you enter. They do not request device GPS or infer a precise live location. A public meet-up/general-area snapshot becomes visible only when you explicitly choose it for a listing.",
  ] },
  { id: "listings", title: "7. Listing and Product Content", paragraphs: [
    "Listings store the title, description, category, condition, price, photos, listing type, seller reference, chosen public location and status. Published listings and photos are public marketplace content; drafts are account-managed content.",
    "Images are processed and stored to display listings and profile photos. Do not include unnecessary personal information in images. This notice does not promise that all uploaded images remove embedded metadata.",
    "Published reviews can include ratings, predefined tags and comments about an eligible buyer or seller role. Private review submissions and deal details use authorised account or participant access. Authentic limited ratings/history may remain after identity minimisation under the deletion rules.",
    "If you save a listing-promotion request, TAKEME stores the seller/listing reference, chosen package/type, example price/duration, request/payment-setup status and timestamps. Checkout, payment and paid activation remain unavailable; saving a request does not buy extra placement or take a payment.",
  ] },
  { id: "communications", title: "8. Messaging, Offers and Auctions", paragraphs: [
    "TAKEME processes private participant conversations, plain-text message bodies, sender/participant references, timestamps, listing/deal/offer context, previews and unread counts to provide marketplace communication. These conversations are not public content. The current messenger does not support attachments, typing indicators or read receipts.",
    "Offers/counters store participants, proposed or agreed amounts, status, expiry and supported payment-arrangement labels. Deals record participant confirmations, cancellation/dispute information and review eligibility. These are marketplace agreement records, not payment-card data or a platform payment receipt.",
    "Auctions record starting amounts, increments, timing, bids, bidder references, current/final amounts and results. Public auction presentation can show amounts/results and limited bidder information without private account emails. Required history preserves genuine auction outcomes.",
    "Relevant bounded message or deal context may be reviewed by authorised staff when necessary for a report, safety concern, dispute or support investigation. This does not mean staff routinely read all messages. Another participant can retain their own copies outside TAKEME.",
  ] },
  { id: "preferences", title: "9. Saved, Following and Preferences", paragraphs: [
    "TAKEME stores your Saved listings/auctions, followed sellers, explicitly saved searches and their supported filters/alert preferences. Those relationships and personal preferences are private; a public seller profile can show an aggregate follower count without exposing follower identities.",
    "In-app Updates contain relevant listing/deal references, notification text, creation/read/open times, unread summaries and preferences. Optional supported alert categories can be managed in Settings; essential offer, deal, dispute and auction-win updates remain enabled.",
    "These preferences affect supported in-app alerts. Native push, marketplace email/SMS alerts and daily digests are not active in the current web service. Authentication password-reset emails are separate.",
  ] },
  { id: "technical", title: "10. Technical and Security Data", paragraphs: [
    "TAKEME records relevant activity/operation identifiers, timestamps, account-linked rate-control counters, upload authorisations and operation outcomes needed for service reliability, safe retries and abuse prevention. Such identifiers can remain linked to an account; they are not automatically anonymous.",
    "Authentication and hosting providers may process network, request and browser information necessary to deliver and secure their services. That provider processing is distinct from TAKEME marketplace records. Current app source does not implement device fingerprinting or a dedicated collection of exact IP addresses, advertising identifiers, device contacts or precise live GPS.",
    "Operational logs should contain only information reasonably needed for security and troubleshooting. Provider/log detail and bounded retention require final review; this notice does not claim every technical record is erased by live account cleanup.",
  ] },
  { id: "support", title: "11. Support, Reports and Disputes", paragraphs: [
    "Support communications use the contact email you choose to write to. Reports can contain the reporter, target, reason, details, status and relevant listing, seller or bounded conversation/message context. Deal disputes can contain participant reasons and resolution records.",
    "Authorised personnel may review relevant evidence and private administration notes where necessary for support, safety, fraud prevention, dispute handling or legal compliance. Ordinary unrelated users cannot access restricted reports, support evidence, administrative notes or deletion/security records.",
    "Provide relevant, truthful information without unnecessary sensitive details. A report does not guarantee an outcome, response time, refund or automatic dispute resolution. Case evidence is subject to restricted, bounded retention rather than permanent default storage.",
  ], links: [{ href: "mailto:" + marketplaceOperator.supportEmail, label: "Contact TAKEME support" }] },
  { id: "acceptance", title: "12. Policy Acceptance Evidence", paragraphs: [
    "TAKEME stores private, server-authored evidence of explicit acceptance: the accepted Terms and Privacy versions, 18+ confirmation, server-controlled timestamps, web source and supported release context. It also keeps a bounded current eligibility record used to check protected marketplace actions.",
    "Acceptance history is immutable during ordinary acceptance and reacceptance: new consent does not overwrite earlier valid evidence, and retries do not create fabricated consent. Historical records are still personal data subject to the approved account-deletion cleanup; immutable does not mean permanent retention.",
    "Only explicit acceptance creates or updates consent evidence. Login, refresh, status checks or browsing alone never count as acceptance. Earlier valid evidence is preserved with its original timestamps where the reviewed migration applies; missing consent is not invented.",
    "This evidence establishes current eligibility, preserves compliance evidence and supports future reacceptance. It does not include a birth date, identity document, IP address, browser fingerprint, cookies or authentication tokens.",
  ] },
  { id: "uses", title: "13. How We Use Personal Data", bullets: [
    "Create and manage accounts, authenticate owners and apply supported account/lifecycle controls.",
    "Display public listings/profiles and enable messages, offers, auctions, agreed deals, Saved, following and in-app Updates.",
    "Provide relevant discovery where implemented and honour supported preferences.",
    "Support users, investigate reports/disputes and prevent fraud or abuse.",
    "Protect service security/reliability, enforce the Terms, maintain required records and comply with applicable law.",
    "Manage explicit policy acceptance/reacceptance and account-deletion requests.",
  ], paragraphs: [
    "The purposes are tied to the supported marketplace and necessary compliance/operation. This notice does not introduce broad advertising profiling or collection for unavailable features.",
  ] },
  { id: "compliance", title: "14. Legal, Compliance and Security Purposes", paragraphs: [
    "Relevant account, marketplace, acceptance and case records may be used to enforce the Terms, establish eligibility, respond to lawful requests, investigate fraud/security concerns and maintain records where applicable law requires it. Use and disclosure should be limited to the legitimate purpose.",
    "LEGAL REVIEW REQUIRED — exact statutory requirements, marketplace/operator duties, retention and deletion conflicts, breach notification obligations and DPO applicability. This draft does not claim a completed compliance certification or an appointed Data Protection Officer.",
  ] },
  { id: "operations", title: "15. Marketplace Operation Purposes", paragraphs: [
    "The service uses listing/profile content for public display and discovery, participant records for messages/offers/deals, auction data for bid ordering/results, and Saved/following/preferences for the supported account features and alerts.",
    "Records of confirmations, reviews, notifications and operation identifiers support truthful marketplace history, safe retries and service reliability. TAKEME does not fabricate payment, shipment, bid or deal outcomes.",
    "Private data is not made public merely because it is used to operate a feature. Account email, private addresses, inbox, acceptance evidence and personal preference records remain outside ordinary public marketplace projections.",
  ] },
  { id: "discovery", title: "16. Personalisation and Discovery", paragraphs: [
    "For signed-in users, supported listing/auction views, submitted searches, category/filter actions, saves, bids, messaging actions, recommendation impressions/clicks, Not interested/Undo and completed-deal activity can generate marketplace signals.",
    "Private interest profiles, records of items actually served and click/save attribution help rank relevant items, avoid repeated exposure, honour supported choices and measure marketplace feature activity. Authorised administration can use aggregate measures.",
    "This is activity within TAKEME, not a record of browsing other websites. Private addresses do not drive public discovery projections. The current implementation does not build an external behavioural-advertising profile.",
  ] },
  { id: "fraud", title: "17. Fraud and Abuse Prevention", paragraphs: [
    "Ownership/participant checks, operation records and bounded rate-control records help detect or prevent repeated abusive messages, offers, bids, reports, listing/draft activity or uploads. Relevant reported content can be considered for a legitimate safety investigation.",
    "Security/fraud evidence is not an indefinite default archive. Any explicit restricted hold requires a documented purpose, restricted access and expiry under the reviewed model. Final legal grounds and retention/deletion reconciliation remain LEGAL REVIEW REQUIRED.",
  ] },
  { id: "providers", title: "18. Service Providers", paragraphs: [
    "Firebase/Google Cloud provides Authentication, Cloud Firestore, Cloud Storage and Cloud Functions for identity, marketplace records, uploaded photos, authorised operations and scheduled processing. Google is also the sign-in provider where you choose Google authentication; Google-hosted profile photos may be displayed.",
    "The reviewed hosting architecture uses Cloudflare Workers to deliver the website and process web requests. Netlify remains a temporary hosting/rollback provider during migration. Support and privacy enquiries use the published Gmail contact; this is not a claim of an integrated support-ticket platform.",
    "Providers process relevant information to deliver, authenticate, host and protect the service. Their infrastructure, technical logs and backups have handling separate from TAKEME live marketplace cleanup.",
    "LEGAL REVIEW REQUIRED — final provider disclosure details, actual services active at public launch, processing arrangements and bounded provider/log retention. No unverified processing country or all-services location guarantee is supplied by this draft.",
  ], links: [{ href: "https://firebase.google.com/support/privacy", label: "Firebase privacy and security information" }] },
  { id: "sharing", title: "19. Data Sharing", paragraphs: [
    "TAKEME does not sell personal data to advertisers. It does not sell personal data as a marketplace service. There is no active external advertising tracker or third-party marketing analytics SDK in the current web implementation.",
    "Data sharing is limited to relevant marketplace visibility, participant communication, service providers and necessary lawful administration, safety or legal purposes. Publishing a listing does not make your account email, private address, inbox, acceptance history or preferences public.",
    "Where applicable and necessary, limited information may be supplied to authorities under law or for lawful fraud/security investigations or relevant legal advice. This draft does not claim routine sharing with insurers, auditors or a corporate buyer where no such current practice is established.",
  ], bullets: [
    "Marketplace visitors see the public profile, listing, review and selected public-location content you publish.",
    "Conversation/deal participants receive information needed for their interaction.",
    "Relevant providers process information needed to host, authenticate and operate the service.",
    "Authorised personnel review relevant account/case information only for legitimate support, safety, administration or legal purposes.",
  ] },
  { id: "transfers", title: "20. International and Cross-Border Processing", paragraphs: [
    "Service providers may process or store data outside Malaysia depending on their infrastructure and service arrangements. A selected Functions region does not establish the location of every service, backup or operational log.",
    "LEGAL REVIEW REQUIRED — final international-transfer language, applicable conditions/safeguards, actual provider arrangements and processing locations. No country is named without verification and no claim is made that all data stays in Malaysia.",
  ] },
  { id: "retention", title: "21. Retention", paragraphs: [
    "Active account/profile and marketplace data is held while needed for its supported purposes, subject to applicable law and the approved retention model. The deletion-related periods below are not a global lifetime for every active account record.",
    "Cleanup removes or minimises personal live data and limits necessary pseudonymised marketplace history and restricted evidence. Pseudonymised records are not necessarily anonymous. An expiry field or pending cleanup is not proof that every physical copy has already disappeared.",
    "LEGAL REVIEW REQUIRED — Malaysian marketplace record-retention requirements and their reconciliation with existing deletion periods, the exact applicable records/start points, and any necessary statutory retention. This draft does not change backend schedules or silently extend records to a new statutory duration.",
  ], bullets: [
    "Successful deletion-operation and audit records: 30 days after completion under the approved cleanup rules.",
    "Surviving counterparty message history: up to 90 days after the relevant deal closes; conversation history without a deal is bounded to 90 days from cleanup, subject to an approved restricted evidence hold.",
    "Minimal pseudonymised closed deals and associated marketplace history: bounded to 12 calendar months under the approved cleanup rules. Deal-linked history uses closure; some associated history uses its cleanup date.",
    "Closed report/dispute evidence: up to 180 days after closure. Open cases remain restricted until valid resolution.",
    "Security/fraud evidence: an explicit documented purpose, restricted access and expiry are required; there is no indefinite default hold.",
    "Backups and operational logs: separate limited periods and deletion-safe restoration procedures require review and operation outside synchronous live cleanup.",
  ] },
  { id: "deletion", title: "22. Account Deletion", paragraphs: [
    "You can request account deletion in Settings or through the public account-deletion route after signing in and confirming ownership with the existing authentication provider. A request, pending state or failed attempt is not completed deletion. Production deletion execution remains off pending separate qualification and activation approval.",
    "The implemented cleanup removes or minimises the public profile, private addresses, saved meet-up places, Saved/following/searches, preferences, notifications, personal discovery records and acceptance history. Safe listings/drafts and owned uploads are cleaned up when their stage permits. Necessary live auction context remains until obligations resolve.",
    "Departing authored messages and copied previews are removed/redacted, identity becomes Deleted user, and necessary counterparty history is bounded. Reviews about the deleted profile are removed; limited genuine ratings/tags about surviving members can remain with departing identity/free-text minimised. TAKEME does not fabricate or rewrite marketplace outcomes.",
    "Live bid-bearing auctions, unfinished deals, unresolved reports/disputes or uncertain legacy obligations can keep a request pending. Fraud/security investigations, legal holds or statutory duties may also lawfully delay or limit deletion, subject to LEGAL REVIEW REQUIRED reconciliation; this is not a claim that every such hold is already an automatic blocker.",
    "Final success is shown only after required cleanup and Firebase Auth deletion succeed. Some data can be removed promptly and some retained or pseudonymised temporarily. Backups, logs and other users' copies may not disappear immediately; no immediate all-data erasure is promised.",
  ], links: [{ href: "/account-deletion", label: "Account deletion details and request" }] },
  { id: "holds", title: "23. Legal Holds, Disputes, Backups and Logs", paragraphs: [
    "Relevant report/dispute or fraud/security evidence can require restricted handling while a valid case or obligation remains. Explicit security/fraud holds require a documented purpose and expiry. Open report/dispute evidence can await valid resolution before its bounded closure-based expiry is set. A generic claim of statutory retention does not automatically resolve the necessary legal scope.",
    "Protected backups and operational logs are outside synchronous live deletion. They should retain only what is reasonably necessary for security, troubleshooting, fraud prevention, disaster recovery and legal duties, for limited documented periods.",
    "The approved restoration procedure requires deletion state/cleanup to be reapplied before restored deleted-user data becomes active again. Backups must not revive a deleted account except where technically necessary for disaster recovery or required by lawful security procedures. These are operational requirements, not a claim that every recovery path is already automated or every backup has expired.",
    "LEGAL REVIEW REQUIRED — legal holds, disputes, backups/log periods, restoration controls and statutory retention/deletion conflicts. This notice does not create an indefinite evidence store.",
  ] },
  { id: "security", title: "24. Security", paragraphs: [
    "TAKEME uses technical and organisational safeguards designed to protect data, including authenticated and authorised access and restricted handling of private records. No online service can guarantee absolute security.",
    "Keep credentials and verification codes private, use accounts you own and avoid unnecessary personal data in public content or Chat. Contact TAKEME if you suspect an account or privacy problem.",
    "LEGAL REVIEW REQUIRED — applicable breach notification obligations, incident responsibilities and DPO applicability. No final statutory response deadline, automatic breach notification system or absolute-security promise is approved by this draft.",
  ] },
  { id: "rights", title: "25. Your Rights Under Applicable Law", paragraphs: [
    "Where applicable under Malaysian law, you may request access to or correction of personal data, withdraw consent where relevant, seek limits on processing provided by law, raise a privacy complaint or request account deletion subject to lawful obligations and retention limits.",
    "Contact " + marketplaceOperator.privacyLegalEmail + " with your request. A reasonable ownership/identity check may be needed before private data is disclosed or changed. Do not send passwords or verification codes. You can also use supported profile, preferences and deletion controls.",
    "Withdrawing consent or declining current acceptance can affect protected features. Public browsing does not itself create consent. A privacy enquiry or withdrawal request does not promise automatic erasure of records required for a lawful purpose or by law.",
    "LEGAL REVIEW REQUIRED — final statutory-rights wording, applicable exceptions, request process and complaint avenues. This draft does not automatically promise GDPR-style rights, universal portability or an invented response deadline.",
  ], links: [{ href: "mailto:" + marketplaceOperator.privacyLegalEmail, label: "Privacy enquiries" }, { href: "/profile/settings", label: "Manage account settings" }] },
  { id: "age", title: "26. Children and Minimum Age", paragraphs: [
    "TAKEME V1 requires account users to be at least " + privacyDocument.minimumAge + " years old (18+). Users below 18 should not create an account or use protected marketplace features. No child-account functionality is provided.",
    "Signup requires an explicit 18+ confirmation. TAKEME does not currently collect a date of birth or independently verify age through identity documents or biometrics. Do not misrepresent your age or submit unnecessary information about children.",
  ] },
  { id: "storage", title: "27. Browser Storage, Cookies and Analytics", paragraphs: [
    "Firebase Authentication can retain sign-in state in browser storage where supported so the account session can persist. The SDK may use browser/session/cache mechanisms necessary to operate authentication. Signing out affects the supported session flow; provider and browser copies follow their handling.",
    "The current web source does not enable a persistent Firestore offline cache, Firebase Analytics, marketing pixels or a third-party advertising tracker. Necessary provider delivery/authentication mechanisms are distinct from TAKEME's recorded marketplace activity. This notice does not introduce marketing cookies or cross-website tracking.",
    "Supported marketplace activity is used for discovery and feature measurement as described above. LEGAL REVIEW REQUIRED — final provider/browser-storage disclosure and any required choices at public launch. Any future analytics/cookie collection needs a new review before activation.",
  ] },
  { id: "changes", title: "28. Changes to This Notice", paragraphs: [
    "Privacy version " + privacyDocument.version + " uses the central V1 policy source. Its effective date is the actual owner-approved public launch date and last updated uses that date unless separately changed. Both dates remain unresolved in this draft; no date or activation is invented.",
    "Material changes should have a clear version, date and appropriate notice or consent as required by applicable law. New users must explicitly accept the current Privacy and Terms versions and confirm 18+ before protected writes; existing users with outdated acceptance may browse public content but must reaccept before protected actions.",
    "Login and refresh never count as Privacy acceptance. Reacceptance preserves earlier evidence and supported profile/welcome state. Returning to an intended context does not automatically execute marketplace actions such as sending a message, bidding, offering, Save, Follow or publishing.",
    "LEGAL REVIEW REQUIRED — final English Privacy legal approval and final BM Privacy wording. The Bahasa Melayu owner draft remains subject to final legal review and is not approved for publication. New payments, shipping, push, native SDKs or other new data practices require further disclosure review.",
  ], links: [{ href: "/terms", label: "Read the Terms of Service draft" }] },
  { id: "contact", title: "29. Contact", paragraphs: [
    marketplaceOperator.name + ". SSM Registration No. " + marketplaceOperator.registrationNumber + ". Privacy and support: " + marketplaceOperator.privacyLegalEmail + ".",
    "Business/correspondence address: " + privacyDocument.businessAddressStatus + ". No address is published in this draft and no private/home address is substituted.",
    "LEGAL REVIEW REQUIRED — final English Privacy approval, final BM notice, publishable address and the unresolved provider, transfer, statutory-rights and retention decisions described above.",
  ], links: [{ href: "mailto:" + marketplaceOperator.privacyLegalEmail, label: "Contact " + marketplaceOperator.privacyLegalEmail }, { href: "/contact", label: "Contact information" }, { href: "/help", label: "Help Centre" }] },
];
